### ISSUE TITLE
metrica legend: count vs. frequency

### ISSUE THREAD

**Issue by JFsanchezherrero** [adriancorrendo/metrica#25]
Hi there @adriancorrendo,

Thanks for the package, it is a great tool for data visualization.

I wonder how can I fix this issue I am encountering here regarding legends and colours.

![image](https://user-images.githubusercontent.com/20244642/189492166-891f1746-7eb6-480a-9197-35a65aeef4c3.png)

I would like to plot two different datasets, left and right, and include them together to compare them. I have created both using `metrica::tiles_plot` and then used ggpubr or grid.arrange. 

The thing is each dataset would set different colours according to the count of each combination. So, comparing them is difficult, they should be using the same scale. If I set a common legend it would not be real.

I have tried to set `scale_fill_gradientn` with a limited number of breaks but I get same results.

```
## original code
metrica::tiles_plot(data = data_given, 
                      obs = P, 
                      pred = E, 
                      bins = 20, orientation = "PO", colors=c(low="#f4c2cd", high="#576ca8"))

## modified
metrica::tiles_plot(data = data_given, 
                      obs = P, 
                      pred = E, 
                      bins = 20, orientation = "PO") +
  scale_fill_gradientn(colours = c("#f4c2cd", "#576ca8"), 
                         breaks = c(10, 20, 30, 40, 50, 60, 70, 80,90, 100))
```

I have also tried density_plot, but I guess I get the same issue here regarding scale. 
![image](https://user-images.githubusercontent.com/20244642/189492654-285a470d-6e56-4ad1-9f65-282b26899fea.png)

For the type of data I have here, integer data and not floating, I prefer to plot data using tiles instead of density plot. So, I guess a solution might be to plot the "proportion of the count" or the frequency instead of the total "count" in the tiles plot.

Thanks in advance,
Jose F. Sanchez

**Comment by adriancorrendo** [comment]
Hi, Jose!

Thanks for the question!

Within the scale_fill_gradientn() you also have to pass the "limits" argument because the `breaks` argument doesn't actually change the scale limits...so I would try with the following:

**scale_fill_gradientn(colours = c("#f4c2cd", "#576ca8"), breaks = seq(0,100, by = 10), limits = c(0,100) )**

Please, let me know if this works!

Best,

ADRIAN

**Comment by adriancorrendo** [comment]
Based on the nature of your data, discrete, I would recommend to use an evaluation as if it were a classification model. So you may use a confusion matrix instead...I may result easier for visualization...You have a function within the same package called confusion_matrix().

You could take a look over here:
[https://adriancorrendo.github.io/metrica/articles/classification_case.html](https://adriancorrendo.github.io/metrica/articles/classification_case.html)

## Example
### Data
`multi_maize_phen <- metrica::maize_phenology`

### Plot
multi_maize_phen %>% 
        confusion_matrix(obs = actual, pred = predicted, 
                                      plot = TRUE, unit = "count")+
        scale_fill_gradientn(colours = c("#f4c2cd", "#576ca8"), breaks = seq(0,100, by = 10), limits = c(0,100) )+
        scale_color_gradientn(colours = c("#f4c2cd", "#576ca8"), breaks = seq(0,100, by = 10), limits = c(0,100) )

![image](https://user-images.githubusercontent.com/46946511/189506560-7fe28e09-fafc-4c85-937b-eaaec39881f5.png)

Hope it helps,

Best,

ADRIAN

**Comment by JFsanchezherrero** [comment]
Hi there @adriancorrendo,
Thank you very much for quick response and suggestions. 

It does work great! Thank you very much. I thought just setting the breaks should be enough but now I see the point in adding the limits too.

I have also checked the confusion_matrix function and it is really cool, definitely. I just have to flip the coordinates in the Y axis to match the tiles or the density plot.

Now, I wonder if it is possible to include the counts in the tiles plot, somehow merging the confusion matrix and the tiles plot. I guess I can map the coordinates and set the count in the background in each tile. I think it would be a great option to include in your function so that future users can plot it too. Also, I think setting the proportion instead of count would be very useful too.

Best regards

Jose

**Comment by adriancorrendo** [comment]
Thanks, Jose

If you check the options of the confusion_matrix() function, you can change the "count" for "proportion" within the 'unit' argument.

For the tiles plot, including a function to print the count may result too crowded and it is a little beyond the scope of the figure, which is thought for continuous variables.

I will think about a suitable plotting option for cases like yours and see what news I can bring!

Cheers,

Adrián 

ADRIAN

**Comment by JFsanchezherrero** [comment]
Thank you very much Adrian.

It makes total sense.

Best regards,
Jose
