### ISSUE TITLE
Showing datasets for different groups

### ISSUE THREAD

**Issue by KeLiu7** [adriancorrendo/metrica#27]
Dear all, @adriancorrendo @lhmrosso @Carlitosh @cbrueffer @leombastos 

Here is the structure of my datasets. 

![image](https://user-images.githubusercontent.com/72141690/191143680-fe444c57-41d9-45ec-b28a-0cafabaf6e41.png)

Currently, I can only evaluate the prediction performance for each year.
![image](https://user-images.githubusercontent.com/72141690/191144005-7c23f20b-c0e3-4e25-9a74-6d4da256ffcf.png)

Do you know how to evaluate the prediction performance with all datasets together but show the label for each point (I have attached the example for your reference)? Many thanks for your suggestions😊

![image](https://user-images.githubusercontent.com/72141690/191144138-0ac42a45-b4a4-44bc-9e32-fe3cf5beb723.png)

**Comment by adriancorrendo** [comment]
Hi, 

I think this can be solved by simply adding a new layer (geom_point) assigning a color or fill by a column that specifies the subgroup.

Please, see the following example:

wheat <- metrica::wheat %>% mutate(crop = "wheat")
barley <- metrica:: barley %>% mutate(crop = "barley")

pooled_data <- wheat %>% bind_rows(., barley)

# Plot
metrica::scatter_plot(data = pooled_data, 
                      obs = obs, pred = pred, 
                      print_metrics = TRUE, 
                      print_eq = TRUE,
                      metrics_list = c("RMSE", "RRMSE", "KGE"),
                      shape_size = 0,
                      shape_type = 1,
                      shape_color = "white")+
  # Add new geom with shape fill by subgroup ("crop")
  geom_point(data = pooled_data, 
             aes(x = obs, y = pred, fill = crop), shape = 21)

![image](https://user-images.githubusercontent.com/46946511/191170456-5d1367c5-bd08-4061-a132-ac706faccda7.png)

**Comment by adriancorrendo** [comment]
Hope it helps!!! Thanks!

**Comment by KeLiu7** [comment]
> Hope it helps!!! Thanks!

Thanks. it works now!
