### ISSUE TITLE
Customized plotting functions in Metrica 

### ISSUE THREAD

**Issue by Amit1979-UniBonn** [adriancorrendo/metrica#9]
Dear Adrian, 
Thanks for creating this very useful package "Metrica". Very easy to use even for someone who is a newbie in using R. However, I couldn't customize the plots as per my requirements. Would it be possible making it more flexible?
Thanks in advance.

**Comment by adriancorrendo** [comment]
Dear Amit,

Please check on the development version of metrica v1.3.0.
Among other updates, it includes new arguments to the plot functions allowing to customize the location of the metrics table (position_metrics = c(x=, y=) ) and the equation (position_eq = c(x=, y=)).

Hope this helps!

Best,

ADRIAN

**Comment by Amit1979-UniBonn** [comment]
Dear Adrian, It's perfectly working. I can position the metric table and the line equation as per need.
Thanks for your efforts.

Bests, 
Amit
